server:
  port: 8081

spring:
  application:
    name: shop
  devtools:
    restart:
      enabled: true
  main:
    allow-bean-definition-overriding: true

  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/ui_db

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 4
        order_inserts:  true

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - refresh
  endpoint:
    health:
      show-details: always

spring-doc:
  version: 1.0
